// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearerAuth handles BearerAuth security.
	HandleBearerAuth(ctx context.Context, operationName string, t BearerAuth) (context.Context, error)
}

func (s *Server) securityBearerAuth(ctx context.Context, operationName string, req *http.Request) (context.Context, error) {
	var t BearerAuth
	scheme, token, ok := strings.Cut(req.Header.Get("Authorization"), " ")
	if !ok {
		return nil, errors.New("invalid bearer auth")
	}
	if !strings.EqualFold(scheme, "Bearer") {
		return nil, errors.Errorf("invalid auth scheme: %q", scheme)
	}
	t.Token = token
	return s.sec.HandleBearerAuth(ctx, operationName, t)
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides BearerAuth security value.
	BearerAuth(ctx context.Context, operationName string) (BearerAuth, error)
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
