openapi: "3.0.0"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://localhost/

components:
  securitySchemes:
    BearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  schemas:      
    Pet: 
      type: object
      properties:
        name:
          type: string

paths:
  /test:
    get:
      security:
        - BearerAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
             schema:
              $ref: "#/components/schemas/Pet"
        404:
          description: bad request
  /me:
    get:
      responses:
        200:
          description: hello
